# -*- coding: utf-8 -*-
"""twitter scraping and cleaning the tweets

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K8GQJB6k8Oh2hK3a4MSk785Sls_qBadq
"""

!pip install selenium
!apt-get update # to update ubuntu to correctly run apt install
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
import time
import requests
from datetime import datetime
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import pandas as pd

text_list = []
time_list = []
ref_dates = []

df_dates = pd.read_csv('/content/btc.csv')

"""***Twitter scraping***"""

for i in range(0,74):
  search_url = 'https://twitter.com/search?q=(Bitcoin%2C%20OR%20bitcoin%2C%20OR%20crypto%2C%20OR%20Crypto%2C%20OR%20BTC)%20until%3A'
  Date_start = str(df_dates['first'][i])
  url_add = '%20since%3A'
  Date_end = str(df_dates['last'][i])
  url_end = '&src=typed_query'
  url = search_url + Date_end + url_add + Date_start + url_end
  driver.get(url)
  WebDriverWait(driver, timeout=15).until(lambda d: d.find_element(By.XPATH, '//div[@data-testid = "tweetText"]'))
  driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
  time.sleep(2) 
  text1 = driver.find_elements(By.XPATH, '//div[@data-testid = "tweetText"]')
  for j in range(len(text1)):
    text_list.append(text1[j].text)
  for k in range(len(text1)):
    ref_dates.append(str(df_dates['datetime'][i]))

ziplst  = list(zip(ref_dates, text_list))
df_1 = pd.DataFrame(ziplst, columns = ['Reference date', 'Tweet text'])

"""***Cleaning the tweets***"""

df_1 = df_1.replace(to_replace =r'http\S+', value = '', regex = True)
df_1 = df_1.replace(to_replace =r'twitter.com/\S+', value = '', regex = True)
df_1 = df_1.replace(to_replace = '[^A-z ]',value = '', regex = True)

"""***Merging the dataframes***"""

df_dates['Reference date'] = pd.to_datetime(df_dates['datetime'])
df_1['Reference date'] = pd.to_datetime(df_1['Reference date'])
df_mer = pd.merge(df_1,df_dates, how = 'inner', on = 'Reference date')
df_mer = df_mer.drop(['Unnamed: 0_x','Unnamed: 0_y','index','datetime'], axis = 1)


df_mer.to_csv('tweets.csv')
